### ISSUE TITLE
Directory links not working.

### ISSUE THREAD

**Issue by nareshkatta99** [Decentralized-ID/decentralized-id.github.io#7]
When I click on any link in directory, it is saying that page not found.

**Comment by infominer33** [comment]
can you be more specific?

as there are over 100 pages on the web-site.. some links are sure to be broken. Hopfully at least it's not the internal links.

we need a system for finding and updating all broken links.. I have a few ideas on how to automate the process, but am probably a ways off from that..

**Comment by nareshkatta99** [comment]
I think I got the answer.
But as you asked me to be specific,

In repo's ReadMe.md there is a section titled Directory.
I wanted to read about [Evolution of SSI](https://github.com/didecentral/decentralized-id.com/blob/master/_pages/self-sovereign-identity/evolution-of-ssi.md). When I clicked on that link, it showing me the 404/Not Found page.

**Comment by infominer33** [comment]
oooh yes, I see! The readme is last to get updated.. and that manually created directory is asking for trouble..
This page of the web-site has a version of that directory seems to be in better condition than the readme.
https://decentralized-id.com/awesome-decentralized-id/

However, if you just go to the homepage, all of the pages within the site are listed in an easier to navigate fashion.

https://decentralized-id.com/

Thanks for bringing that to my attention!

For the short term solution I copied the source of the index on our website which is more updated than the readme, and at least if there is a broken link they will land on the website which is easier to navigate than this github repository

please let do share if you have any other suggestions or improvements.
